### PR TITLE
fixed #hostname, broken in 1.1.4

### PR DESCRIPTION
**Pull request by onoga**

### CODE REVIEW

**Comment by wardle** [comment]
Hi. It would be great to see this merged, as this bug has just bitten me. Thanks @onoga for creating this PR.

**Comment by source-c** [comment]
> Hi. It would be great to see this merged, as this bug has just bitten me. Thanks @onoga for creating this PR.

Hey! You are not alone with that issue. Since the original library is not maintained any more we hard-forked it as https://github.com/dkdhub/edn-config and applied all the patches required for normal production use. You are welcome to use it as drop in replacement if you wish.

**Comment by wardle** [comment]
Thanks @source-c

**Review by joelittlejohn — APPROVED** [review]

**Comment by wardle** [comment]
Thank you

**Pull request merged**
