### PR TITLE
handle absolute include paths in relative-resolver

### PR DESCRIPTION
**Pull request by mrmcc3**

### CODE REVIEW

**Comment by malcolmsparks** [comment]
Oh - we were thinking along the same lines - I'll merge the test of this PR later on.

**Comment by mrmcc3** [comment]
No worries. 

The tests should also check `missing-include` for all resolvers. At the moment only the relative-resolver will handle missing includes.

With regards to the current implementation IMO all resolvers should return `nil` if they cannot resolve. https://github.com/juxt/aero/blob/master/src/aero/core.clj#L85 could be moved to the 'include defmethod and apply to all resolvers. This should also work for custom resolvers that are maps when key lookup fails

Also what are your thoughts on invalid edn in included files? Should we follow the same approach and replace with `{:invalid-edn "path-to-include"}`

I might put together another PR if i have some spare time in the next few days.

**Comment by malcolmsparks** [comment]
Yes, I need to add a test for the case of the missing file. I was in a bit of a hurry yesterday and testing the new functionality on our juxt.pro website that uses Aero heavily which was failing due to the missing file (in one of our profiles). We use #include to bring in a local secrets.edn as explained in https://juxt.pro/blog/posts/aero.html, and the dev profile was failing because there are no secrets in dev. So I made the snap decision to return the `{:missing-include ...}`value.

I agree that user-provided resolvers should return nil if they can't resolve. Some will anyway, and it's very idiomatic to wrap code in `when` guards etc. Aero should support that, but for its own error conditions I think it should be as helpful as possible in error situations. Configuration has a tendency to become opaque and difficult to debug (especially in stressful situations like outages!) and we should prefer good diagnostics whenever possible. 

However, I do think `:invalid-edn` and other keywords should be `:aero/invalid-edn` to support error detection. There should be an `:aero/error true` in each such map. Also, it would be useful to catch any exceptions from resolvers and add them to the maps too. `:aero/error e`.

**Comment by malcolmsparks** [comment]
There is a [Reddit discussion](https://www.reddit.com/r/Clojure/comments/4hud2o/juxts_aero_library/) about Aero which introduces the idea of using (keywhiz-fs)[https://github.com/square/keywhiz-fs] to provide centralised management of secrets files. Definitely worth a look.

**Comment by mrmcc3** [comment]
Ah yeah good point w.r.t resolvers having the ability to provide better diagnostics over just a simple `:missing-include`.

**Comment by mrmcc3** [comment]
Some more thoughts on this. 

Replacing invalid edn / bad includes with aero error maps `{:aero/error true :aero/missing-include ...}` is good for readability/feedback in development over obscure error messages. However I think bad includes and invalid edn really are programmer mistakes and should fail with an exception (ideally with better error messages). 

For example I can imagine a situation in production where there is a bad include, aero reads the config fine and then you get an error (possibly unrelated to config) in a component or some other part of the system. You'd have to chase it back to config which isn't ideal. 

It might be a good idea to move the provided resolvers to their own namespace and impl. some custom error handling around missing/bad files/resources etc.

**Pull request closed without merging**
