### PR TITLE
use resolvers for custom includes

### PR DESCRIPTION
**Pull request by mrmcc3**

### CODE REVIEW

**Comment by malcolmsparks** [comment]
Very welcome. Let me test this today/tomorrow and if all does well I'll merge. Thanks for this!

**Comment by malcolmsparks** [comment]
I'm getting failures when using #include on absolute file paths, e.g.

```
java.lang.IllegalArgumentException: /home/malcolm/.secrets.edn is not a relative path
```

I think Aero should cope with this case. Raising issue #20. Happy to keep this merged however.

**Comment by mrmcc3** [comment]
Agreed. The obvious fix would be to improve the `relative-resolver` (which is the default) to check for absolute include paths.

**Comment by malcolmsparks** [comment]
Yes, I've just done this.

**Comment by malcolmsparks** [comment]
Just deployed 1.0.0-beta5

**Pull request merged**
